# Generated by Django 3.0.2 on 2020-01-15 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=50)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliations', to='accounts.Contributor')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliations', to='services.Service')),
            ],
            options={
                'ordering': ('contributor__points',),
            },
        ),
        migrations.CreateModel(
            name='AvaliationFeedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField()),
                ('avaliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='avaliations.Avaliation')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliation_feedbacks', to='accounts.Contributor')),
            ],
            options={
                'ordering': ('contributor__points',),
            },
        ),
    ]
